In [1]:
import numpy as np
import io
import urllib
import requests


In [2]:
# simple test function that retrieves a complete file and returns its size
# can switch between urllib and requests library
def get_url(url,use_requests=False):
    data=urllib.request.urlopen(url).read()
    print("%s : \nsize of data [bytes] : %d"%(url,len(data)))
    return data

In [3]:
# listing in HTML
u='http://virgo02/turbdb'
%time r=get_url(u)

http://virgo02/turbdb : 
size of data [bytes] : 100100
CPU times: user 24.9 ms, sys: 10.1 ms, total: 35.1 ms
Wall time: 48.3 ms


In [10]:
%%time
u='http://virgo02/turbdb/turbdb108_0.bin'
#%time 
d=get_url(u)
n=int(len(d)/4)
#%time _arr=np.frombuffer(d,dtype=np.float32,count=n)
_arr=np.frombuffer(d,dtype=np.float32,count=n)
d=None
#%time 
print("# cells", n,", average value:",np.average(_arr))



http://virgo02/turbdb/turbdb108_0.bin : 
size of data [bytes] : 1610612736
# cells 402653184 , average value: 0.106146
CPU times: user 1.56 s, sys: 4.79 s, total: 6.36 s
Wall time: 6.46 s


In [11]:
%%time
dsp_url = 'http://dsp060/disk0'+str(k+1)+'/filedb/turbulence/turbdb10'+str(k+1)+'_0.bin'
d=get_url(dsp_url)
n=int(len(d)/4)
#%time _arr=np.frombuffer(d,dtype=np.float32,count=n)
_arr=np.frombuffer(d,dtype=np.float32,count=n)
d=None
#%time 
print("# cells", n,", average value:",np.average(_arr))

http://dsp060/disk08/filedb/turbulence/turbdb108_0.bin : 
size of data [bytes] : 1610612736
# cells 402653184 , average value: 0.106146
CPU times: user 1.53 s, sys: 4.59 s, total: 6.12 s
Wall time: 6.1 s


In [12]:
%%time 

N = 1024
farr = np.zeros((N**3,),dtype='float32')
nx = N//8
stride = nx*N*N

for k in range(8):
    u = 'http://virgo02/turbdb/turbdb10'+str(k+1)+'_0.bin' 
    d=get_url(u)
    n=int(len(d)/4)
    _arr=np.frombuffer(d,dtype=np.float32,count=n)
    #farr[k*stride:(k+1)*stride] = _arr[:]
    d=None

http://virgo02/turbdb/turbdb101_0.bin : 
size of data [bytes] : 1610612736
http://virgo02/turbdb/turbdb102_0.bin : 
size of data [bytes] : 1610612736
http://virgo02/turbdb/turbdb103_0.bin : 
size of data [bytes] : 1610612736
http://virgo02/turbdb/turbdb104_0.bin : 
size of data [bytes] : 1610612736
http://virgo02/turbdb/turbdb105_0.bin : 
size of data [bytes] : 1610612736
http://virgo02/turbdb/turbdb106_0.bin : 
size of data [bytes] : 1610612736
http://virgo02/turbdb/turbdb107_0.bin : 
size of data [bytes] : 1610612736
http://virgo02/turbdb/turbdb108_0.bin : 
size of data [bytes] : 1610612736
CPU times: user 7.55 s, sys: 38.7 s, total: 46.3 s
Wall time: 47.5 s


In [14]:
%%time 

N = 1024
farr = np.zeros((N**3,),dtype='float32')
nx = N//8
stride = nx*N*N

for k in range(8):
    #u = 'http://virgo02/turbdb/turbdb10'+str(k+1)+'_0.bin' 
    dsp_url = 'http://dsp060/disk0'+str(k+1)+'/filedb/turbulence/turbdb10'+str(k+1)+'_0.bin'
    d=get_url(dsp_url)
    n=int(len(d)/4)
    _arr=np.frombuffer(d,dtype=np.float32,count=n)
    #farr[k*stride:(k+1)*stride] = _arr[:]
    d=None

http://dsp060/disk01/filedb/turbulence/turbdb101_0.bin : 
size of data [bytes] : 1610612736
http://dsp060/disk02/filedb/turbulence/turbdb102_0.bin : 
size of data [bytes] : 1610612736
http://dsp060/disk03/filedb/turbulence/turbdb103_0.bin : 
size of data [bytes] : 1610612736
http://dsp060/disk04/filedb/turbulence/turbdb104_0.bin : 
size of data [bytes] : 1610612736
http://dsp060/disk05/filedb/turbulence/turbdb105_0.bin : 
size of data [bytes] : 1610612736
http://dsp060/disk06/filedb/turbulence/turbdb106_0.bin : 
size of data [bytes] : 1610612736
http://dsp060/disk07/filedb/turbulence/turbdb107_0.bin : 
size of data [bytes] : 1610612736
http://dsp060/disk08/filedb/turbulence/turbdb108_0.bin : 
size of data [bytes] : 1610612736
CPU times: user 9.45 s, sys: 50.6 s, total: 1min
Wall time: 1min 7s


# Cutting chunks

In [55]:
# single chunk is easy
ncells=512
ranges=[(0,ncells*3*4-1)]
# url of a file
url='http://virgo02/turbdb/turbdb101_30.bin'
# define the Range HTTP header
headers={"Range":"bytes=%s" % ",".join("%d-%d" % (g) for g in ranges)}
# retrieve the data
resp=requests.get(url,headers=headers,stream=True)
if resp.status_code != 206:
    print("error in response code ",resp.status_code)
d=resp.raw.read()
n=int(len(d)/4)
%time _arr=np.frombuffer(d,dtype=np.float32,count=n)
%time print("# cells", n,", average value:",np.average(_arr))


CPU times: user 39.1 ms, sys: 282 ms, total: 321 ms
Wall time: 353 ms
# cells 1536 , average value: -0.470825
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 982 µs


In [56]:
# when >1 ranges present, more complex
# assuming the data are organized in 12-byte triples, of 3 floats
# define a few ranges that will retrieve these tiples
ranges=[(0,11), (12,23),(24,47),(144,155)]
# url of a file
url='http://virgo02/turbdb/turbdb101_30.bin'
# define the Range HTTP header
headers={"Range":"bytes=%s" % ",".join("%d-%d" % (g) for g in ranges)}
# retrieve the data
resp=requests.get(url,headers=headers,stream=True)
if resp.status_code != 206:
    print("error in response code ",resp.status_code)
# if there are multiple ranges, the result is a complex structure defined by the Content-Type header
# which defines a boundary separating the byte streams of the individual ranges
# the next few lines define this boundary which will be used to cut up the complete content
ct=resp.headers['Content-Type']
boundary=ct.split("=")[1]
boundary=("--%s"%boundary).encode()
print("boundary=",boundary)

# first cut up the raw content using the boundary
chunks=resp.raw.read().split(boundary)
count=0;ncount=0;
for chunk in chunks:
    # each chunk has still some crap around it that needs to be removed as well
    ix=chunk.find(b"Content-Range")
    if ix<0:
        continue
    chunk=chunk[ix:-2]
    chunk=chunk[chunk.find(b'\r\n\r\n')+4:]
    # now the chunk is a pure array of bytes, the length of which should be given by the range
    
    _range=ranges[count]
    # define the length of the arryay of 4-byte floats
    n=int((_range[1]-_range[0]+1)/4 )
    # read the array
    narr=np.frombuffer(chunk,dtype=np.float32,count=n)
    print(narr)
    count+=1

boundary= b'--<q1w2e3r4t5y6u7i8o9p0zaxscdvfbgnhmjklkl>'
[-0.65512633 -1.03012335 -0.11621436]
[-0.63719344 -1.04078746 -0.12809123]
[-0.61377287 -1.0589366  -0.12283614 -0.58266103 -1.05651009 -0.10981002]
[-0.55073839 -1.02768779 -0.03384927]
